### ISSUE TITLE
Minerals get used for meteorites and dont always work right

### ISSUE THREAD

**Issue by zachary-foster** [zachary-foster/Minerals#16]

**Comment by sidfu** [comment]
while them being in metorites is fine just how they land is issue. the glass one landed and it had 20 on 1 tile so clicking on it caused lag. u can probaly conuslt sky with how the fix the issue as he fixed a simlar issue with amber metorites

**Comment by zachary-foster** [comment]
Thanks @sidfu! I take a look at how the amber ones are set up and ask sky if it is not clear

**Comment by zachary-foster** [comment]
Now dropped minerals are full size and only only a single one is dropped
