### ISSUE TITLE
Issue with loading a saved game.

### ISSUE THREAD

**Issue by Metamaniac** [zachary-foster/Minerals#22]
When reloading a saved game all minerals will jump to 100% in size.

**Comment by zachary-foster** [comment]
Thanks for the report! I will try to reproduce the bug this weekend

**Comment by zachary-foster** [comment]
Does it only happen in a save before the last update, or on a save without updating?

**Comment by Metamaniac** [comment]
It happens on every version.

**Comment by zachary-foster** [comment]
Ok, I just confirmed it. I am surprised I have not noticed that before. Also breaks stacking of minerals.

**Comment by zachary-foster** [comment]
Should be fixed in 0.4.3. Let me know if it still happens. Thanks!

**Comment by Metamaniac** [comment]
This is fixed as far as i can tell, though it does require a new game. Older games running on the newest version will have the sizes of minerals reduced to 0%.

Good work.
